IF (HAVE_CRYPTOPP)
	message(STATUS "Found CACHED Crypto++ in ${CRYPTOPP_SOURCE_DIR}")
ELSE (HAVE_CRYPTOPP)
	find_path(CRYPTOPP_SOURCE_DIR NAMES crypto++/cryptlib.h cryptopp/cryptlib.h)
	
	IF (CRYPTOPP_SOURCE_DIR)
		message(STATUS "Found Crypto++ in ${CRYPTOPP_SOURCE_DIR}")
		set(HAVE_CRYPTOPP TRUE)
	ELSE (CRYPTOPP_SOURCE_DIR)
		message(STATUS "Crypto++ was not found in ${CRYPTOPP_SOURCE_DIR} (CRYPTOPP_SOURCE_DIR)")
	ENDIF (CRYPTOPP_SOURCE_DIR)

ENDIF (HAVE_CRYPTOPP)

IF (HAVE_CRYPTOPP)
	message(STATUS "Using Crypto++ from ${CRYPTOPP_SOURCE_DIR}")
	find_library(CRYPTOPP_LIBRARIES NAMES cryptopp)

ENDIF (HAVE_CRYPTOPP)
