set(EVENT_INCLUDE_DIRS "EVENT_INCLUDE_DIRS-NOTFOUND")
set(EVENT_LIBRARIES "EVENT_LIBRARIES-NOTFOUND")

FIND_PATH(EVENT_INCLUDE_DIRS ev.h PATH_SUFFIXES include/ev include include/libev)

SET(EVENT_NAMES ${EVENT_NAMES} ev libev)
FIND_LIBRARY(EVENT_LIBRARIES NAMES ${EVENT_NAMES} PATH)

IF(EVENT_INCLUDE_DIRS AND EVENT_LIBRARIES)
SET(HAVE_EVENT TRUE)
file(APPEND src/transport_config.h "#define WITH_LIBEVENT 1\n")
ELSE(EVENT_INCLUDE_DIRS AND EVENT_LIBRARIES)
SET (EVENT_INCLUDE_DIRS "")
SET (EVENT_LIBRARIES "")
ENDIF(EVENT_INCLUDE_DIRS AND EVENT_LIBRARIES)

IF(HAVE_EVENT)
MESSAGE(STATUS "Found libev: ${EVENT_LIBRARIES}")
ENDIF(HAVE_EVENT)
