INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PURPLE purple)

# IF(PURPLE_FOUND)
# 	SET(PURPLE_INCLUDE_DIRS
# 		${PURPLE_INCLUDE_DIRS}
# 		)
# 
# 	SET(PURPLE_LIB_DIRS
# 		${PURPLE_LIBRARY_DIRS}
# 		)
# 
# 	SET(PURPLE_LIBS
# 		${PURPLE_LIBRARIES}
# 		)
# 
# 	SET(K3D_PURPLE_FOUND 1)
# ENDIF(PURPLE_FOUND)
