#!/bin/sh
#
# spectrum (this script) - manage multiple spectrum (XMPP Transport) instances
# Copyright (C) 2009 Thilo Cestonaro <thilo@cestona.ro> and 
# Mathias Ertl <mati@fsinf.at>
# 
# Distributable under the terms of the GNU GPL version 2.
#

### BEGIN INIT INFO
# Provides:             spectrum
# Required-Start:       $network $local_fs $remote_fs
# Required-Stop:
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Spectrum XMPP Transport Service
### END INIT INFO

USER=spectrum
CONFSDIR=/etc/spectrum/

# Check that user exists
check_user() {
	if ! getent passwd $USER >/dev/null; then
		exit 1;
	fi
}

. /lib/lsb/init-functions

start() {
    for i in $CONFSDIR/*.cfg ; do
      if grep "enable" $i | grep "=" | grep "1" > /dev/null ; then
        CONF=`basename $i`
        log_daemon_msg "Starting spectrum instance:" "$CONF"
	spectrumctl --su $USER -q -c $i start
	log_end_msg $?
      fi
    done
}

stop() {
    for i in $CONFSDIR/*.cfg ; do
      if grep "enable" $i | grep "=" | grep "1" > /dev/null ; then
        CONF=`basename $i`
        log_daemon_msg "Stopping spectrum instance:" "$CONF"
	spectrumctl -q -c $i stop
	log_end_msg $?
      fi
    done
}

reload() {
    for i in $CONFSDIR/*.cfg ; do
      if grep "enable" $i | grep "=" | grep "1" > /dev/null ; then
        CONF=`basename $i`
        log_daemon_msg "Reloading spectrum instance:" "$CONF"
	spectrumctl -q -c $i reload
	log_end_msg $?
      fi
    done
}

case "$1" in
  start)
    check_user
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  reload)
    reload
    ;;
  force-reload)
    reload
    ;;
  *)
    log_action_msg "Usage: /etc/init.d/spectrum {start|stop|restart|reload|force-reload}"
    exit 1
esac
      
exit 0;
